### ISSUE TITLE
About the MAttNet visual feature.

### ISSUE THREAD

**Issue by ChopinSharp** [daqingliu/NMTree#1]
Hello. I've been trying to reproduce the result of this paper. Could you be more specific about how to extract the MAttNet feature used during training? 

The training command in README requires a "matt_res_det_feats.pth" file. But I followed the instructions in MAttNet repository, extracted features using Mask R-CNN, and finally got a bunch of ".h5" files.

Any help would be appreciated~ Thanks in advance!

**Comment by daqingliu** [comment]
Sorry for the late reply, you know, CVPR deadline.
I have updated https://github.com/daqingliu/MAttNet, hope this helps.

**Comment by ChopinSharp** [comment]
It works. Thanks a lot!
By the way, I think the "--visual_feat_file" option in the training command should be set to "matt_res_gt_feats.pth" rather than "matt_res_det_feats.pth", because ground truth are needed during training. Using "matt_res_det_feats.pth" would cause an error.

**Comment by daqingliu** [comment]
@ChopinSharp Yes, you are right! Fixed :)
