### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte

### ISSUE THREAD

**Issue by abhinavkaul95** [daqingliu/NMTree#3]
Hi,
I am trying to reproduce the results. During training using the following command,

`python tools/train.py --id det_nmtree_01 --dataset refcocog --split_by umd --grounding_model NMTree --data_file data_dep --batch_size 128 --glove glove.840B.300d_dep --visual_feat_file matt_res_gt_feats.pth`

I am getting the following error:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte`

I have downloaded the MAttNet features and done the preprocessing part. All the settings are default.

The requirements installed are as follows:
blis==0.7.4
cached-property==1.5.2
catalogue==2.0.1
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
cymem==2.0.5
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0-py3-none-any.whl
h5py==3.2.1
idna==2.10
importlib-metadata==3.7.3
Jinja2==2.11.3
MarkupSafe==1.1.1
murmurhash==1.0.5
numpy==1.20.1
packaging==20.9
pathy==0.4.0
Pillow==8.1.2
pkg-resources==0.0.0
preshed==3.0.5
pydantic==1.7.3
pyparsing==2.4.7
requests==2.25.1
six==1.15.0
smart-open==3.0.0
spacy==3.0.5
spacy-legacy==3.0.1
srsly==2.4.0
thinc==8.0.2
torch==1.4.0
torchvision==0.5.0
tqdm==4.59.0
typer==0.3.2
typing-extensions==3.7.4.3
urllib3==1.26.4
wasabi==0.8.2
zipp==3.4.1

Complete console logs and error stacktrace as follows:
```
Loader loading data.json:  data/feats/refcocog_umd/data_dep.json
word vocab size is  6751
object category size is  80
we have 25799 images.
we have 208960 anns.
we have 49822 refs.
we have 95010 sentences.
loading visual feats ...
Traceback (most recent call last):
  File "tools/train.py", line 263, in <module>
    main(opt)
  File "tools/train.py", line 59, in main
    loader = GtLoader(data_json, visual_feats_dir, opt, data_pth)
  File "/media/disk/user/abhinav/NMTree/tools/../utils/gt_loader.py", line 33, in __init__
    map_location=lambda storage, loc: storage, pickle_module=pickle)
  File "/media/disk/user/abhinav/NMTree/venv/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/media/disk/user/abhinav/NMTree/venv/lib/python3.7/site-packages/torch/serialization.py", line 702, in _legacy_load
    result = unpickler.load()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte
```

**Comment by daqingliu** [comment]
Please change the Pytorch version to 1.3.0 (or 1.0.0? I am not very sure). This error is due to the torch.load() function.

**Comment by abhinavkaul95** [comment]
Thanks @daqingliu. Torch 1.0.0 works!

**Comment by nevinmusula** [comment]
hey,

Thanks for your work. i am trying out your algorithm on colab pro. Got the same error. I have installed Torch 1.0.0 but doesn't still work. I get the following


Loader loading data.json:  data/feats/refcocog_umd/data_dep.json
word vocab size is  6793
object category size is  80
we have 25799 images.
we have 208960 anns.
we have 49822 refs.
we have 95010 sentences.
loading visual feats ...
^C

what could be the problem?
