### ISSUE TITLE
No such file or directory: 'data/detections/refcocog_umd/res101_coco_minus_refer_notime_dets.json'

### ISSUE THREAD

**Issue by abhinavkaul95** [daqingliu/NMTree#4]
Hi @daqingliu,

Trying to run eval_det,py using the command,
`python  tools/eval_det.py --id det_nmtree_01 --log_path log --dataset refcocog --split_by umd`

I am getting the following error:
`FileNotFoundError: [Errno 2] No such file or directory: 'data/detections/refcocog_umd/res101_coco_minus_refer_notime_dets.json'`

Could you please tell from where and how can I get the json?

**Comment by daqingliu** [comment]
This dets boxes file is detected by a Mask RCNN as [MattNet](https://github.com/lichengunc/MAttNet). Here is the file [download link](http://bvision.cs.unc.edu/licheng/MattNet/detections.zip) including 'refcocog_umd/res101_coco_minus_refer_notime_dets.json'.

**Comment by abhinavkaul95** [comment]
Thanks @daqingliu,

The problem is there are lots of issues actually training MAttNet. I also needed the file matt_res_det_feats.pth and I am not able to find it anywhere, not in their README also. I have [asked](https://github.com/lichengunc/MAttNet/issues/40) the author also.

If you have the download link for that, please feel free to share the link or otherwise feel free to close the issue.
